name: sokrates-ai
region: ams3
services:
  - name: web
    source_dir: /
    github:
      repo: dnassehi/sokrates-ai
      branch: main
    run_command: pnpm start
    build_command: pnpm run postinstall && pnpm run build
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    min_instance_count: 1
    public_ports:
      - 3000
    routes:
      - path: /
    envs:
      - key: NODE_ENV
        value: production
      - key: BASE_URL
        value: ${BASE_URL}
      - key: BASE_URL_OTHER_PORT
        value: ${BASE_URL_OTHER_PORT}
      - key: ADMIN_PASSWORD
        value: ${ADMIN_PASSWORD}
      - key: OPENAI_API_KEY
        value: ${OPENAI_API_KEY}
      - key: ASSISTANT_ID
        value: ${ASSISTANT_ID}
      - key: ANAMNESIS_MODEL
        value: gpt-4o
      - key: JWT_SECRET
        value: ${JWT_SECRET}
      - key: DATABASE_URL
        value: ${db.DATABASE_URL}
      - key: PORT
        value: "3000"
    health_check:
      http_path: /
      initial_delay_seconds: 60
      interval_seconds: 10
      timeout_seconds: 10
      success_threshold: 1
      failure_threshold: 3
databases:
  - name: postgres
    engine: PG
    version: "15"
    size: db-s-1vcpu-1gb
    private_connection: true
